### ISSUE TITLE
[Selección de personaje] Player 1, Personaje seleccionado no coincide con el nombre

### ISSUE THREAD

**Issue by martincaroc** [sabasa28/AniBrawl#3]
### Descripción del bug. 

En la selección de personajes por defecto ambos jugadores tienen seleccionado un gato, pero en el caso del jugador uno la descripción es la de un pato. A pesar de que cambiemos de personaje este mensaje no cambia.

**Pasos de reproducción**

1. Desde el menú principal darle a play

2. Cambiar de personaje en el jugador uno (tanto como izquierda, como derecha)

3. Cambiar de personaje en el jugador dos (repetir el segundo paso)

**Resultado:** La descripción del personaje del jugador uno, no coincide con la seleccionada.

**Frecuencia de reproducción:** *4/4* 

**Versión:** _0.6v_
[Video adjunto](https://drive.google.com/file/d/1xnTIXxIXm_OfRzFf2HfU_LwiabzyEEkH/view?usp=sharing)

**Comment by sabasa28** [comment]
Arreglado en la version v0.11

**Comment by CDMedina87** [comment]
Se realizó prueba de regresión en Versión 0.11 confirmando que el bug fue solucionado.
